# rand2: average logLikelihood=-3.409865497511346 median logLikelihood=-2.743386891525006
# rand4: average logLikelihood=-3.541503003413527 median logLikelihood=-3.321391654200852
# rand6: average logLikelihood=-3.6978498170815874 median logLikelihood=-3.321410972625017
# rand8: average logLikelihood=-3.635281379122607 median logLikelihood=-3.4960558759921696
# best number of break points (average logLikelihood):2
# best number of break points (median logLikelihood):2
# Step 1: estimations for the "final" result
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-1.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-2.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-3.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-4.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-5.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-6.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-7.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-8.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-9.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-10.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-11.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-12.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-13.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-14.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-15.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-16.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-17.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-18.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-19.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-20.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-21.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-22.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-23.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-24.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-25.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-26.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-27.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-28.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-29.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-30.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-31.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-32.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-33.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-34.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-35.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-36.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-37.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-38.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-39.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-40.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-41.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-42.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-43.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-44.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-45.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-46.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-47.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-48.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-49.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-50.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-51.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-52.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-53.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-54.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-55.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-56.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-57.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-58.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-59.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-60.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-61.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-62.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-63.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-64.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-65.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-66.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-67.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-68.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-69.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-70.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-71.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-72.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-73.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-74.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-75.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-76.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-77.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-78.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-79.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-80.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-81.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-82.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-83.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-84.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-85.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-86.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-87.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-88.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-89.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-90.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-91.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-92.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-93.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-94.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-95.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-96.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-97.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-98.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-99.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-100.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-101.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-102.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-103.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-104.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-105.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-106.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-107.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-108.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-109.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-110.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-111.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-112.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-113.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-114.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-115.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-116.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-117.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-118.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-119.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-120.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-121.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-122.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-123.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-124.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-125.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-126.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-127.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-128.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-129.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-130.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-131.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-132.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-133.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-134.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-135.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-136.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-137.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-138.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-139.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-140.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-141.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-142.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-143.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-144.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-145.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-146.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-147.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-148.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-149.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-150.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-151.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-152.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-153.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-154.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-155.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-156.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-157.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-158.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-159.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-160.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-161.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-162.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-163.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-164.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-165.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-166.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-167.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-168.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-169.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-170.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-171.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-172.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-173.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-174.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-175.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-176.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-177.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-178.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-179.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-180.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-181.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-182.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-183.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-184.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-185.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-186.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-187.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-188.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-189.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-190.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-191.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-192.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-193.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-194.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-195.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-196.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-197.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-198.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-199.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
cp -f ./reduction_sweep/output_stairwayplot2/cerevisiae/rand2/cerevisiae-200.2_0.99.addTheta ./reduction_sweep/output_stairwayplot2/cerevisiae/final/
# Step 2: create summaries and plots
java -Xmx4g -cp ./bin/stairway_plot_es/:./bin/stairway_plot_es/gral-core-0.11.jar:./bin/stairway_plot_es/VectorGraphics2D-0.9.3.jar Stairway_output_summary_plot2 ./reduction_sweep/output_stairwayplot2/cerevisiae.blueprint
java -Xmx4g -cp ./bin/stairway_plot_es/:./bin/stairway_plot_es/gral-core-0.11.jar:./bin/stairway_plot_es/VectorGraphics2D-0.9.3.jar Stairway_output_summary_plot2 ./reduction_sweep/output_stairwayplot2/cerevisiae.blueprint rand2
java -Xmx4g -cp ./bin/stairway_plot_es/:./bin/stairway_plot_es/gral-core-0.11.jar:./bin/stairway_plot_es/VectorGraphics2D-0.9.3.jar Stairway_output_summary_plot2 ./reduction_sweep/output_stairwayplot2/cerevisiae.blueprint rand4
java -Xmx4g -cp ./bin/stairway_plot_es/:./bin/stairway_plot_es/gral-core-0.11.jar:./bin/stairway_plot_es/VectorGraphics2D-0.9.3.jar Stairway_output_summary_plot2 ./reduction_sweep/output_stairwayplot2/cerevisiae.blueprint rand6
java -Xmx4g -cp ./bin/stairway_plot_es/:./bin/stairway_plot_es/gral-core-0.11.jar:./bin/stairway_plot_es/VectorGraphics2D-0.9.3.jar Stairway_output_summary_plot2 ./reduction_sweep/output_stairwayplot2/cerevisiae.blueprint rand8
