# rand49: average logLikelihood=-183.7109953782121 median logLikelihood=-183.48420828286908
# rand99: average logLikelihood=-183.1560887954604 median logLikelihood=-182.88959958570194
# rand148: average logLikelihood=-183.76261733217996 median logLikelihood=-183.69549301589723
# rand198: average logLikelihood=-182.54783800508392 median logLikelihood=-182.6687613048416
# best number of break points (average logLikelihood):49
# best number of break points (median logLikelihood):49
# Step 1: estimations for the "final" result
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-1.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-2.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-3.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-4.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-5.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-6.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-7.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-8.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-9.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-10.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-11.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-12.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-13.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-14.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-15.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-16.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-17.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-18.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-19.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-20.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-21.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-22.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-23.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-24.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-25.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-26.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-27.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-28.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-29.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-30.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-31.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-32.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-33.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-34.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-35.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-36.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-37.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-38.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-39.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-40.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-41.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-42.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-43.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-44.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-45.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-46.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-47.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-48.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-49.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-50.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-51.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-52.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-53.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-54.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-55.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-56.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-57.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-58.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-59.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-60.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-61.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-62.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-63.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-64.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-65.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-66.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-67.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-68.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-69.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-70.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-71.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-72.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-73.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-74.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-75.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-76.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-77.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-78.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-79.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-80.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-81.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-82.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-83.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-84.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-85.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-86.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-87.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-88.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-89.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-90.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-91.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-92.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-93.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-94.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-95.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-96.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-97.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-98.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-99.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-100.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-101.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-102.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-103.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-104.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-105.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-106.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-107.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-108.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-109.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-110.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-111.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-112.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-113.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-114.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-115.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-116.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-117.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-118.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-119.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-120.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-121.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-122.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-123.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-124.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-125.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-126.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-127.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-128.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-129.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-130.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-131.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-132.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-133.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-134.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-135.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-136.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-137.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-138.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-139.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-140.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-141.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-142.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-143.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-144.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-145.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-146.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-147.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-148.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-149.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-150.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-151.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-152.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-153.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-154.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-155.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-156.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-157.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-158.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-159.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-160.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-161.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-162.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-163.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-164.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-165.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-166.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-167.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-168.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-169.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-170.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-171.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-172.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-173.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-174.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-175.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-176.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-177.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-178.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-179.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-180.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-181.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-182.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-183.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-184.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-185.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-186.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-187.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-188.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-189.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-190.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-191.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-192.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-193.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-194.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-195.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-196.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-197.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-198.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-199.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
cp -f ./expansion_sweep/output_stairwayplot2_50/cerevisiae/rand49/cerevisiae-200.49_0.99.addTheta ./expansion_sweep/output_stairwayplot2_50/cerevisiae/final/
# Step 2: create summaries and plots
java -Xmx4g -cp ./bin/stairway_plot_es/:./bin/stairway_plot_es/gral-core-0.11.jar:./bin/stairway_plot_es/VectorGraphics2D-0.9.3.jar Stairway_output_summary_plot2 ./expansion_sweep/output_stairwayplot2_50/cerevisiae.blueprint
java -Xmx4g -cp ./bin/stairway_plot_es/:./bin/stairway_plot_es/gral-core-0.11.jar:./bin/stairway_plot_es/VectorGraphics2D-0.9.3.jar Stairway_output_summary_plot2 ./expansion_sweep/output_stairwayplot2_50/cerevisiae.blueprint rand49
java -Xmx4g -cp ./bin/stairway_plot_es/:./bin/stairway_plot_es/gral-core-0.11.jar:./bin/stairway_plot_es/VectorGraphics2D-0.9.3.jar Stairway_output_summary_plot2 ./expansion_sweep/output_stairwayplot2_50/cerevisiae.blueprint rand99
java -Xmx4g -cp ./bin/stairway_plot_es/:./bin/stairway_plot_es/gral-core-0.11.jar:./bin/stairway_plot_es/VectorGraphics2D-0.9.3.jar Stairway_output_summary_plot2 ./expansion_sweep/output_stairwayplot2_50/cerevisiae.blueprint rand148
java -Xmx4g -cp ./bin/stairway_plot_es/:./bin/stairway_plot_es/gral-core-0.11.jar:./bin/stairway_plot_es/VectorGraphics2D-0.9.3.jar Stairway_output_summary_plot2 ./expansion_sweep/output_stairwayplot2_50/cerevisiae.blueprint rand198
